# -*- coding: utf-8 -*-
"""Copia de arbolBinario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eDB8D17aHMBbHUbkn1t_UJqVBYbAuY9H
"""

!pip install binarytree

from binarytree import build

values = [40, 20, 45, 11, 15, 30, 78]
root = build(values)
print(root)

from binarytree import Node
root = Node(40)
root.left = Node(20)
root.right = Node(45)
root.left.left = Node(11)
root.left.right = Node(15)
root.right.left = Node(30)
root.right.right = Node(78)
print(root)